### PR TITLE
Files needed for MinGW-w64 testing

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by certik** [comment]
Are these binaries? If so, how did you create them, or where do they come from?

**Comment by isuruf** [comment]
Links for the last 2 commits are given in the commit message.
GMP dlls, I compiled them in a appveyor VM using MinGW-w64 and MSYS

**Comment by certik** [comment]
Ok, very good, I missed those links. Yes, after our last experience, we should definitely host these ourselves.

We should add a README with step by step instructions how to create the GMP dll, so that it can be reproduced.

**Comment by isuruf** [comment]
How about compiling GMP on each run? I think I can do it now with shell scripts only.

**Comment by certik** [comment]
Does it take long? If not, I would do it on each run for now. 

In the short run, I would only host sources here. Perhaps we can create a new repository to host binaries.
In the long run, we want to probably cache the binaries of GMP. We can probably use Anaconda or something similar.

So why don't you rebase your PR to take the binary commit out, then see if we can build GMP from source, if not, then we can host the binary in a separate repo?

**Comment by isuruf** [comment]
It takes about 5 minutes to build it.
All 3 files added in this PR are binaries. :D

**Comment by certik** [comment]
Let's ship the binary then if it takes 5 minutes. The MPIR with MSVC takes perhaps 30s or so.

Why don't we keep these in a branch, let's call it `binaries` for now. The reason is that I don't know yet if I want to put binaries into the master. If it is on a branch, then one can download it easily.

**Comment by isuruf** [comment]
Closing in favour of #2

**Pull request closed without merging**
